# Generated by Django 3.2.4 on 2021-06-30 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('boardid', models.IntegerField(primary_key=True, serialize=False)),
                ('boardname', models.CharField(max_length=50)),
                ('cre_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='boardcontent',
            fields=[
                ('boardcontentid', models.IntegerField(primary_key=True, serialize=False)),
                ('cre_date', models.DateTimeField()),
                ('hit', models.IntegerField()),
                ('isnotice', models.BooleanField()),
                ('content', models.TextField()),
                ('boardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='board.board')),
            ],
        ),
        migrations.CreateModel(
            name='chatroom',
            fields=[
                ('chatroomid', models.IntegerField(primary_key=True, serialize=False)),
                ('chatroomname', models.CharField(max_length=50)),
                ('cre_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('replyid', models.IntegerField(primary_key=True, serialize=False)),
                ('cre_date', models.DateTimeField()),
                ('reply', models.TextField()),
                ('boardcontentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_replied', to='board.boardcontent')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, unique=True)),
                ('pw', models.CharField(max_length=300)),
                ('signdate', models.DateTimeField()),
                ('expiredate', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('auth', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='rereply',
            fields=[
                ('rereplyid', models.IntegerField(primary_key=True, serialize=False)),
                ('cre_date', models.DateTimeField()),
                ('rereply', models.TextField()),
                ('replyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_rereplied', to='board.reply')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_name_rereplied', to='board.user')),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_id_replied', to='board.user'),
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('boardcontentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_or_dislike_this', to='board.boardcontent')),
                ('cipherid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_like', to='board.user')),
            ],
        ),
        migrations.CreateModel(
            name='chatusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroomname', models.CharField(max_length=25)),
                ('cre_date', models.DateTimeField()),
                ('chatroomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_in', to='board.chatroom')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('chatid', models.IntegerField(primary_key=True, serialize=False)),
                ('chatroomid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='where_talk', to='board.chatroom')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='who_chatted', to='board.user')),
            ],
        ),
        migrations.CreateModel(
            name='bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardcontentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_on', to='board.boardcontent')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='board.user')),
            ],
        ),
        migrations.AddField(
            model_name='boardcontent',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_name', to='board.user'),
        ),
    ]
